# Generated by Django 6.0.1 on 2026-01-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_datospersonales_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(choices=[('Tipo A', 'Tipo A'), ('Tipo B', 'Tipo B'), ('Tipo C', 'Tipo C'), ('Tipo D', 'Tipo D'), ('Tipo E', 'Tipo E'), ('Tipo F', 'Tipo F'), ('Tipo G', 'Tipo G')], max_length=6),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.BooleanField(default=True),
        ),
    ]
