# Generated by Django 6.0.1 on 2026-01-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_datospersonales_licenciaconducir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursorealizado',
            name='idcursorealizado',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='idperfil',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='idexperiencialaboral',
        ),
        migrations.RemoveField(
            model_name='productoacademico',
            name='idproductoacademico',
        ),
        migrations.RemoveField(
            model_name='productolaboral',
            name='idproductoslaborales',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='idreconocimiento',
        ),
        migrations.RemoveField(
            model_name='ventagarage',
            name='idventagarage',
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='productoacademico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='productolaboral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
