# Generated by Django 6.0.1 on 2026-01-22 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_alter_ventagarage_estadoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='fechapublicacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='venta_garage/'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40),
        ),
    ]
