# Generated by Django 6.0.1 on 2026-01-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_ventagarage_fechapublicacion_ventagarage_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40),
        ),
    ]
