# Generated by Django 6.0.1 on 2026-01-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_ventagarage_estadoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
