# Generated by Django 6.0.1 on 2026-01-25 03:31

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_alter_productoacademico_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursorealizado',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/cursos/', validators=[cv.models.validar_extension_imagen]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/experiencia/', validators=[cv.models.validar_extension_imagen]),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/reconocimientos/', validators=[cv.models.validar_extension_imagen]),
        ),
    ]
